services:
  # Base de datos PostgreSQL
  workunity-pg-db:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    container_name: workunity-pg-db-container
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - ${DB_PGSQL_PORT_PUBLIC}:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      #- ./init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      workunity-pg-network:
        ipv4_address: 173.28.0.251
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5 # Número de intentos antes de marcar como no saludable
      start_period: 30s #Espera inicial antes de comenzar a comprobar(Dar tiempo a PostgreSQL inicie)

  workunity-web:
    container_name: workunity-web-container
    build:
      context: .
      args:
        # Parámetros para el Dockerfile definido en las variables del archivo .env o sistema para copiar el archivo durante el build.
        # Se usa solo durante la creación de la imagen. No afecta al contenedor en ejecución.
        # Copia el driver JDBC a /config/ dentro de la imagen
        - ENV_DRIVER_JDBC_DIR=${DRIVER_JDBC_DIR}
    image: workunity-app:latest
    environment:
      # Ejecución del contenedor (environment):
      # Open Liberty usa DRIVER_JDBC_DIR=/config/ para ubicar el driver.
      - DRIVER_JDBC_DIR=/config/
      - DB_SERVER_NAME=${DB_SERVER_NAME}
      - DB_PORT_NUMBER=${DB_PORT_NUMBER}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
    ports:
      - "9080:9080"
      - "9443:9443"
    depends_on:
      - workunity-pg-db
    deploy:
      resources:
        limits:
          #cpus: '0.50'
          memory: 1024M
        reservations:
          #cpus: '0.25'
          memory: 512M
    networks:
      workunity-pg-network:
      #ipv4_address: 173.28.0.2



  workunity-pg-adminer-db:
    image: adminer
    container_name: workunity-pg-adminer-db-container
    restart: unless-stopped
    #    restart: always
    ports:
      - 8082:8080
    depends_on:
      - workunity-pg-db
    networks:
      workunity-pg-network:
        ipv4_address: 173.28.0.254

  workunity-pg-admin4-db:
    container_name: workunity-pg-admin4-container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "adminDB@postgres.org"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - 16544:80
    depends_on:
      - workunity-pg-db
    networks:
      workunity-pg-network:
        ipv4_address: 173.28.0.253

networks:
  workunity-pg-network:
    driver: bridge
    #driver_opts:
    #    parent: eth0
    ipam:
      driver: default
      config:
        - subnet: 173.28.0.0/24
volumes:
  pg-data:
    name: workunity-pg-data-local
    driver: local
    driver_opts:
      type: none
      device: ${LOCAL_DATA_DIR_BD}
      o: bind
